# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=50)),
                ('CTC', models.IntegerField()),
                ('Date_of_visit', models.DateField()),
                ('Eligibility', models.CharField(max_length=20)),
                ('Branch', models.CharField(max_length=20)),
            ],
        ),
    ]
